controller_manager:
  ros__parameters:
    update_rate: 50

    # https://github.com/ros-controls/ros2_controllers/tree/master/joint_state_broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
